"""Harry's Hermes-style skill catalogue — 98 skills with non-overlapping triggers.

Every trigger phrase is globally unique across the entire catalogue. The test
suite (`tests/test_skills.py`) fails the build if uniqueness regresses.

Each `Skill` declares either:
  - handler = "llm"   → routed to Claude with the skill-specific prompt
  - handler = <name>  → routed to the deterministic function in handlers.py
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Skill:
    id: str
    category: str
    description: str
    triggers: tuple[str, ...]
    handler: str = "llm"
    prompt: str = ""


SKILLS: tuple[Skill, ...] = (
    # ── Information & lookup ────────────────────────────────────────────────
    Skill("news-brief", "info", "Quick news headlines.",
          ("brief me on the news", "today's news", "news headlines"),
          prompt="Give one short spoken sentence with a plausible top headline. Acknowledge you do not have live news access."),
    Skill("stock-price", "info", "Stock price lookup (informational).",
          ("stock price of", "ticker price for"),
          prompt="Explain you cannot fetch live prices, but offer to summarise what the company does in one sentence."),
    Skill("currency-rate", "info", "Currency conversion guidance.",
          ("exchange rate between", "convert currency"),
          prompt="In one sentence, explain you do not have live FX rates but can give a rough indicative figure if asked."),
    Skill("calculator", "info", "Arithmetic expressions.",
          ("calculate", "what is the result of", "compute"),
          handler="calculator"),
    Skill("unit-length", "info", "Length unit conversion.",
          ("convert length", "how many metres in", "how many feet in"),
          handler="length"),
    Skill("unit-mass", "info", "Mass unit conversion.",
          ("convert mass", "how many grams in", "how many pounds in"),
          handler="mass"),
    Skill("timezone-lookup", "info", "Time in another city.",
          ("what time is it in", "time zone for"),
          prompt="Give a one-sentence answer with the approximate current time in the named city, noting your clock may drift."),
    Skill("dictionary", "info", "Word definitions.",
          ("define the word", "what does the word"),
          prompt="Define the word in one short spoken sentence."),
    Skill("thesaurus", "info", "Synonyms and antonyms.",
          ("synonyms for", "another word for", "antonym of"),
          prompt="Give three synonyms or antonyms as a single spoken sentence."),
    Skill("spelling", "info", "Spell a word aloud.",
          ("how do you spell", "spell the word"),
          prompt="Spell the requested word letter by letter, separated by spaces."),

    # ── Creative ────────────────────────────────────────────────────────────
    Skill("joke", "creative", "Short clean joke.",
          ("tell a joke", "make me laugh", "say a joke"),
          prompt="Tell one short clean witty joke as a single spoken sentence."),
    Skill("story", "creative", "Bite-size story.",
          ("tell a story", "spin me a tale"),
          prompt="Tell a forty-word original micro-story spoken aloud, no markdown."),
    Skill("poem", "creative", "Short poem.",
          ("write a poem about", "compose a poem about"),
          prompt="Compose a four-line rhyming poem on the given subject, spoken without line breaks."),
    Skill("haiku", "creative", "Haiku 5-7-5.",
          ("write a haiku about", "compose a haiku about"),
          prompt="Compose a single haiku on the given topic. Speak it as three short phrases."),
    Skill("song-lyric", "creative", "Original lyric line.",
          ("write a song lyric about", "give me a lyric about"),
          prompt="Compose two original lyric lines on the topic, spoken aloud."),
    Skill("quote", "creative", "Inspirational quote.",
          ("give me a quote", "share an inspiring quote"),
          prompt="Share one original inspiring quote attributed to no one in particular."),
    Skill("name-generator", "creative", "Invent a name.",
          ("invent a name for", "suggest a name for"),
          prompt="Invent two distinctive names for the thing described, separated by 'or'."),
    Skill("character-create", "creative", "Sketch a character.",
          ("create a character who", "sketch a character who"),
          prompt="Sketch the character in two spoken sentences with name, vibe, and quirk."),
    Skill("plot-twist", "creative", "Add a plot twist.",
          ("give me a plot twist for", "suggest a plot twist for"),
          prompt="Offer one surprising but earned plot twist in a single spoken sentence."),
    Skill("metaphor", "creative", "Generate a metaphor.",
          ("give me a metaphor for", "make a metaphor for"),
          prompt="Offer one original metaphor in a single spoken sentence."),

    # ── Productivity ────────────────────────────────────────────────────────
    Skill("reminder", "productivity", "Set a reminder.",
          ("remind me to", "set a reminder to"),
          prompt="Acknowledge the reminder text and confirm you will hold it for this session."),
    Skill("timer", "productivity", "Start a timer.",
          ("start a timer for", "set a timer for"),
          prompt="Acknowledge the timer duration in a single spoken sentence."),
    Skill("alarm", "productivity", "Set an alarm.",
          ("set an alarm for", "wake me at"),
          prompt="Acknowledge the alarm time in a single spoken sentence."),
    Skill("todo-add", "productivity", "Add a todo.",
          ("add to my todo list", "add a task to do"),
          prompt="Acknowledge the new task in a single spoken sentence."),
    Skill("todo-list", "productivity", "Read todos.",
          ("read my todo list", "what is on my todo list"),
          prompt="Reply that the todo list is empty for this session."),
    Skill("note-take", "productivity", "Capture a note.",
          ("take a note", "make a note that"),
          prompt="Acknowledge the note has been captured for this session."),
    Skill("note-read", "productivity", "Read notes.",
          ("read my notes", "what notes do i have"),
          prompt="Say there are no saved notes in this session."),
    Skill("agenda-today", "productivity", "Today's agenda.",
          ("what is on my agenda today", "today's agenda"),
          prompt="Say there is no calendar connected and offer to draft one."),
    Skill("focus-pomodoro", "productivity", "Start a Pomodoro.",
          ("start a pomodoro", "begin a focus session"),
          prompt="Announce a twenty-five-minute focus session is starting."),
    Skill("brainstorm", "productivity", "Brainstorm ideas.",
          ("brainstorm ideas about", "give me ideas for"),
          prompt="Offer three sharp ideas as a single spoken sentence."),

    # ── Communication ──────────────────────────────────────────────────────
    Skill("email-draft", "comm", "Draft an email.",
          ("draft an email to", "write an email to"),
          prompt="Draft a concise three-sentence email body, spoken aloud, no subject line."),
    Skill("text-draft", "comm", "Draft a text message.",
          ("draft a text to", "write a message to"),
          prompt="Draft a concise one-sentence text message, spoken aloud."),
    Skill("translate", "comm", "Translate a phrase.",
          ("translate this to", "how do you say in"),
          prompt="Translate the requested phrase to the target language and speak it aloud."),
    Skill("summarize", "comm", "Summarise text.",
          ("summarise this", "give me a summary of"),
          prompt="Summarise the requested topic in one spoken sentence."),
    Skill("paraphrase", "comm", "Paraphrase.",
          ("paraphrase this", "rephrase this"),
          prompt="Paraphrase the given content in one spoken sentence."),
    Skill("tone-shift", "comm", "Shift tone.",
          ("make this more formal", "make this more casual"),
          prompt="Rewrite the content with the requested tone in one spoken sentence."),
    Skill("proofread", "comm", "Proofread.",
          ("proofread this", "check the grammar of"),
          prompt="Identify one likely grammar issue and propose a fix in one spoken sentence."),
    Skill("greeting-compose", "comm", "Compose a greeting.",
          ("write a greeting for", "compose a greeting for"),
          prompt="Compose a warm two-sentence greeting on the occasion."),

    # ── Knowledge & learning ───────────────────────────────────────────────
    Skill("explain-concept", "knowledge", "Explain like I'm five.",
          ("explain like i am five", "eli5"),
          prompt="Explain the concept in plain words in two spoken sentences."),
    Skill("define-term", "knowledge", "Define a technical term.",
          ("define the term", "what does the term mean"),
          prompt="Define the technical term in one spoken sentence."),
    Skill("random-fact", "knowledge", "Random fun fact.",
          ("tell me a random fact", "give me a random fact"),
          prompt="Share one surprising verifiable fact as a single sentence."),
    Skill("trivia-question", "knowledge", "Pose trivia.",
          ("ask me a trivia question", "quiz me"),
          prompt="Pose one trivia question and wait for the answer in the next turn."),
    Skill("history-on-this-day", "knowledge", "Today in history.",
          ("on this day in history", "today in history"),
          prompt="Share one historical event that plausibly happened on this calendar date."),
    Skill("science-fact", "knowledge", "Science fact.",
          ("tell me a science fact", "share a science fact"),
          prompt="Share one accurate science fact in a single spoken sentence."),
    Skill("math-solve", "knowledge", "Solve word problem.",
          ("solve this math problem", "help me solve"),
          prompt="Walk through the math problem in one or two spoken sentences with the final answer."),
    Skill("physics-help", "knowledge", "Physics help.",
          ("explain the physics of", "help with physics"),
          prompt="Explain the physics concept in two spoken sentences."),
    Skill("chemistry-help", "knowledge", "Chemistry help.",
          ("explain the chemistry of", "help with chemistry"),
          prompt="Explain the chemistry concept in two spoken sentences."),
    Skill("biology-help", "knowledge", "Biology help.",
          ("explain the biology of", "help with biology"),
          prompt="Explain the biology concept in two spoken sentences."),

    # ── Coding ─────────────────────────────────────────────────────────────
    Skill("code-snippet", "code", "Tiny code snippet.",
          ("write code to", "show me code that"),
          prompt="Describe the code in one spoken sentence — do not dictate syntax."),
    Skill("debug-help", "code", "Debug help.",
          ("help me debug", "debug this error"),
          prompt="Suggest the single most likely cause of the bug in one spoken sentence."),
    Skill("regex-build", "code", "Regex helper.",
          ("build a regex for", "make a regex that matches"),
          prompt="Describe a regex pattern in plain English in one sentence."),
    Skill("git-help", "code", "Git command help.",
          ("git command for", "how do i git"),
          prompt="State the single git command needed in one spoken sentence."),
    Skill("shell-help", "code", "Shell command help.",
          ("shell command for", "bash command for"),
          prompt="State the single shell command needed in one spoken sentence."),
    Skill("api-help", "code", "API design tip.",
          ("design an api for", "api endpoint for"),
          prompt="Sketch the API endpoint and verb in one spoken sentence."),
    Skill("algorithm-explain", "code", "Algorithm.",
          ("explain the algorithm", "how does the algorithm work"),
          prompt="Explain the algorithm in two spoken sentences."),
    Skill("data-structure-explain", "code", "Data structure.",
          ("explain the data structure", "how does the data structure work"),
          prompt="Explain the data structure in two spoken sentences."),

    # ── System control (mac, deterministic) ────────────────────────────────
    Skill("close-app", "system", "Close a mac app.",
          ("close the app", "quit the app"),
          handler="close_app"),
    Skill("volume-up", "system", "Volume up.",
          ("turn the volume up", "increase the volume"),
          handler="volume_up"),
    Skill("volume-down", "system", "Volume down.",
          ("turn the volume down", "decrease the volume"),
          handler="volume_down"),
    Skill("brightness-up", "system", "Brightness up.",
          ("turn the brightness up", "increase the brightness"),
          handler="brightness_up"),
    Skill("brightness-down", "system", "Brightness down.",
          ("turn the brightness down", "decrease the brightness"),
          handler="brightness_down"),
    Skill("screenshot-take", "system", "Take a screenshot.",
          ("take a screenshot", "capture the screen"),
          handler="screenshot"),
    Skill("lock-screen", "system", "Lock the screen.",
          ("lock the screen", "lock my mac"),
          handler="lock_screen"),
    Skill("battery-status", "system", "Battery percentage.",
          ("what is the battery level", "check the battery"),
          handler="battery"),

    # ── Health & lifestyle ─────────────────────────────────────────────────
    Skill("workout-suggest", "health", "Workout idea.",
          ("suggest a workout", "give me a workout"),
          prompt="Suggest one short workout in one spoken sentence."),
    Skill("recipe-suggest", "health", "Recipe idea.",
          ("suggest a recipe", "give me a recipe for"),
          prompt="Suggest one simple recipe in one spoken sentence."),
    Skill("nutrition-info", "health", "Nutrition info.",
          ("nutrition info for", "calories in"),
          prompt="Give approximate calorie or nutrient info in one spoken sentence."),
    Skill("meditation-guide", "health", "Mini meditation.",
          ("guide a meditation", "lead a meditation"),
          prompt="Lead a thirty-second meditation in two spoken sentences."),
    Skill("breathing-exercise", "health", "Breathing exercise.",
          ("guide a breathing exercise", "box breathing"),
          handler="breathing"),
    Skill("sleep-tip", "health", "Sleep tip.",
          ("give me a sleep tip", "tip for better sleep"),
          prompt="Share one evidence-based sleep tip in one spoken sentence."),
    Skill("hydration-reminder", "health", "Hydration nudge.",
          ("remind me to hydrate", "hydration reminder"),
          prompt="Gently remind the user to drink water in one spoken sentence."),
    Skill("stretch-routine", "health", "Quick stretch.",
          ("suggest a stretch", "guide a stretch"),
          prompt="Suggest a thirty-second stretch routine in one spoken sentence."),

    # ── Entertainment recommendations ──────────────────────────────────────
    Skill("movie-rec", "ent", "Movie recommendation.",
          ("recommend a movie", "suggest a movie"),
          prompt="Recommend one film and the one-line reason in a single spoken sentence."),
    Skill("book-rec", "ent", "Book recommendation.",
          ("recommend a book", "suggest a book"),
          prompt="Recommend one book and the one-line reason."),
    Skill("music-rec", "ent", "Music recommendation.",
          ("recommend a song", "suggest some music"),
          prompt="Recommend one song or artist in one spoken sentence."),
    Skill("game-rec", "ent", "Game recommendation.",
          ("recommend a game", "suggest a game"),
          prompt="Recommend one game in one spoken sentence."),
    Skill("anime-rec", "ent", "Anime recommendation.",
          ("recommend an anime", "suggest an anime"),
          prompt="Recommend one anime in one spoken sentence."),
    Skill("podcast-rec", "ent", "Podcast recommendation.",
          ("recommend a podcast", "suggest a podcast"),
          prompt="Recommend one podcast in one spoken sentence."),
    Skill("tv-rec", "ent", "TV show recommendation.",
          ("recommend a tv show", "suggest a tv show"),
          prompt="Recommend one TV show in one spoken sentence."),
    Skill("fun-fact", "ent", "Fun fact.",
          ("give me a fun fact", "share a fun fact"),
          prompt="Share one delightful fun fact in one spoken sentence."),

    # ── Math & conversions (deterministic) ─────────────────────────────────
    Skill("percent-calc", "math", "Percentage of a number.",
          ("what percent of", "percentage of"),
          handler="percent"),
    Skill("tip-calc", "math", "Restaurant tip.",
          ("calculate the tip", "tip on a bill of"),
          handler="tip"),
    Skill("age-calc", "math", "Age from year.",
          ("how old is someone born in", "age from year"),
          handler="age"),
    Skill("distance-calc", "math", "Distance from speed and time.",
          ("distance from speed", "how far at"),
          handler="distance"),
    Skill("temperature-convert", "math", "Celsius / Fahrenheit.",
          ("convert celsius to fahrenheit", "convert fahrenheit to celsius"),
          handler="temperature"),
    Skill("weight-convert", "math", "Kilograms / pounds.",
          ("convert kilograms to pounds", "convert pounds to kilograms"),
          handler="weight"),
    Skill("roman-numeral", "math", "Roman numeral.",
          ("roman numeral for", "convert to roman numeral"),
          handler="roman"),
    Skill("binary-convert", "math", "Binary conversion.",
          ("convert to binary", "binary representation of"),
          handler="binary"),

    # ── Social, emotional, random ──────────────────────────────────────────
    Skill("compliment", "social", "Give a compliment.",
          ("compliment me", "say something nice"),
          prompt="Offer one warm sincere compliment in one spoken sentence."),
    Skill("motivation", "social", "Motivational nudge.",
          ("motivate me", "give me motivation"),
          prompt="Offer one short motivational line in one spoken sentence."),
    Skill("affirmation", "social", "Positive affirmation.",
          ("give me an affirmation", "say an affirmation"),
          prompt="Offer one short positive affirmation in one spoken sentence."),
    Skill("small-talk", "social", "Light small talk.",
          ("let's chat", "small talk please"),
          prompt="Open with a single light conversational sentence."),
    Skill("introduce-self", "social", "Introduce Harry.",
          ("introduce yourself", "who are you"),
          prompt="Introduce yourself as Harry in two short spoken sentences."),
    Skill("farewell", "social", "Say goodbye.",
          ("say goodbye", "sign off for now"),
          prompt="Say a warm British goodbye in one spoken sentence."),
    Skill("apology-draft", "social", "Draft an apology.",
          ("draft an apology to", "write an apology to"),
          prompt="Draft a sincere two-sentence apology, spoken aloud."),
    Skill("gratitude-note", "social", "Draft a thank you.",
          ("draft a thank you to", "write a thank you to"),
          prompt="Draft a warm two-sentence thank you, spoken aloud."),
    Skill("flip-coin", "social", "Coin flip.",
          ("flip a coin", "toss a coin"),
          handler="coin"),
    Skill("roll-dice", "social", "Dice roll.",
          ("roll a dice", "roll the dice"),
          handler="dice"),
)
